In [2]:
import tensorflow as tf

In [4]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
result

b'Hello World'

In [14]:
a = tf.constant(10)
b = tf.constant(20)
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [16]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [17]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [18]:
result

30

In [19]:
const = tf.constant(10)


In [24]:
fill_mat = tf.fill((4,4),10)

In [26]:
myzeros = tf.zeros((4,4))

In [27]:
myones = tf.ones((4,4))

In [28]:
myrandn = tf.random_normal((4,4),mean=10,stddev=1)

In [29]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [30]:
my_ops = [const, fill_mat,myzeros,myones,myrandn,myrandu]

In [31]:
sess = tf.InteractiveSession()

In [33]:
for ops in my_ops:
    print(sess.run(ops))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 8.464977 10.738561  9.64815   9.351915]
 [ 9.989146 10.321629  9.233629  8.720772]
 [11.062504  9.95651  10.276908 11.184651]
 [11.042643  8.264877 11.365098 10.144325]]


[[0.5891496  0.18235087 0.12018645 0.02706373]
 [0.93909    0.18837106 0.9656192  0.86514187]
 [0.00754511 0.5991734  0.27418315 0.9663855 ]
 [0.01246011 0.5485045  0.07578886 0.25935698]]




In [35]:
a = tf.constant([[1,2],[3,4]])       

In [36]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [37]:
b = tf.constant([[10],[100]])

In [38]:
result = tf.matmul(a,b)

In [39]:
sess.run(result)

array([[210],
       [430]])

In [ ]:
result.e